/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui {
	import laya.ui.*;
	import laya.display.*;

	public class GameviewUI extends Scene {
		public var lordcard_box:Box;

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"Scene","props":{"width":1282,"height":709},"compId":2,"child":[{"type":"Sprite","props":{"y":0,"x":0,"width":1282,"texture":"sence/BG2.png","height":709},"compId":3},{"type":"Box","props":{"y":23,"x":506,"var":"lordcard_box"},"compId":26,"child":[{"type":"Image","props":{"width":284,"skin":"comp/blank.png","height":103},"compId":14},{"type":"Image","props":{"y":4,"x":23,"skin":"poker/CardBack.png","name":"lordcard_1"},"compId":7},{"type":"Image","props":{"y":4,"x":110,"skin":"poker/CardBack.png","name":"lordcard_2"},"compId":12},{"type":"Image","props":{"y":4,"x":196,"skin":"poker/CardBack.png","name":"lordcard_3"},"compId":13}]}],"loadList":["sence/BG2.png","comp/blank.png","poker/CardBack.png"],"loadList3D":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}