/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui {
	import laya.ui.*;
	import laya.display.*;

	public class GamelobbyUI extends Scene {
		public var singleGame_btn:Button;
		public var enterNetRoom_btn:Button;

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"Scene","props":{"width":1282,"height":709},"compId":2,"child":[{"type":"Sprite","props":{"y":0,"x":0,"width":1282,"texture":"sence/BG4.png","height":709},"compId":3},{"type":"Button","props":{"y":354.5,"x":521,"width":240,"var":"singleGame_btn","skin":"comp/button.png","labelSize":30,"labelFont":"SimHei","label":"单机模式","height":99},"compId":4},{"type":"Button","props":{"y":172,"x":521,"width":240,"var":"enterNetRoom_btn","skin":"comp/button.png","labelSize":30,"labelFont":"SimHei","label":"加入网络房间","height":99},"compId":6},{"type":"TextInput","props":{"y":85,"x":491,"width":299,"text":"000","skin":"comp/textinput.png","prompt":"输入房间号","height":58,"fontSize":50,"font":"SimHei","color":"#ff0400","align":"center"},"compId":7}],"loadList":["sence/BG4.png","comp/button.png","comp/textinput.png"],"loadList3D":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}