/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui {
	import laya.ui.*;
	import laya.display.*;

	public class LoadviewUI extends Scene {
		public var startBtn:Button;
		public var bar:Image;

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"Scene","props":{"width":1282,"height":709},"compId":2,"child":[{"type":"Sprite","props":{"y":0,"x":0,"width":1282,"texture":"sence/BG1.png","height":709},"compId":3},{"type":"Sprite","props":{"y":527,"x":448.5,"texture":"view/load/linebg.png"},"compId":5},{"type":"Button","props":{"y":637,"x":561,"var":"startBtn","skin":"view/load/button_star.png"},"compId":4},{"type":"Image","props":{"y":561,"x":479,"width":10,"var":"bar","skin":"view/load/bars.png","sizeGrid":"0,11,0,11","height":33},"compId":6}],"loadList":["sence/BG1.png","view/load/linebg.png","view/load/button_star.png","view/load/bars.png"],"loadList3D":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}